services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculator
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mariadb
    volumes:
      - ./dbmigrations:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:mariadb://mariadb:3306/calculator
      - FLYWAY_USER=user
      - FLYWAY_PASSWORD=password
    command: migrate
    
  backend:
    image: ghcr.io/anderswith/backend:latest
    container_name: backend
    restart: always
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=calculator
    ports:
      - "5000:5000"

  frontend:
    image: ghcr.io/anderswith/frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mariadb_data: