name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.8.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calculator
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - "3307:3306"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for MariaDB to be ready
        run: |
          echo "Waiting for MariaDB to start..."
          sleep 40  # Give MariaDB time to initialize
          until docker exec $(docker ps -q -f ancestor=mariadb:latest) mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MariaDB..."
            sleep 5
          done
          echo "MariaDB is ready!"

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            --network=host \
            -v $(pwd)/dbmigration:/flyway/sql \
            flyway/flyway:latest \
            -url=jdbc:mariadb://127.0.0.1:3307/calculator
            -user=user -password=password migrate
