name: Database Migration

on:
  push:
    branches:
      - main

jobs:
  migrate-database:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: calculator
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - "3307:3306"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check Docker version
        run: docker --version

      - name: Clean up resources from previous jobs
        run: |
          docker system prune -f
          docker network prune -f

      - name: Create local container network
        run: docker network create local_network

      - name: Start MariaDB service container
        run: |
          docker run -d --name mariadb_service \
            --network=local_network \
            -e MYSQL_ROOT_PASSWORD=root \
            -e MYSQL_DATABASE=calculator \
            -e MYSQL_USER=user \
            -e MYSQL_PASSWORD=password \
            -p 3307:3306 \
            mariadb:latest

      - name: Wait for MariaDB to be ready
        run: |
          echo "Waiting for MariaDB to start..."
          sleep 40  # Give MariaDB time to initialize
          until docker exec mariadb_service mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MariaDB..."
            sleep 5
          done
          echo "MariaDB is ready!"

      - name: Run Flyway migrations
        run: |
          docker run --rm \
            --network=local_network \
            -v $(pwd)/dbmigration:/flyway/sql \
            flyway/flyway:latest \
            -url=jdbc:mariadb://127.0.0.1:3307/calculator \
            -user=user -password=password migrate