on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          SERVER_USER: ${{ vars.STAGING_SERVER_USERNAME }}
          SERVER_IP: ${{ vars.STAGING_SERVER_IP }}
        
        run: |
          # Set up the SSH private key correctly
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Test SSH connection with debug mode
          ssh -o StrictHostKeyChecking=no -v $SERVER_USER@$SERVER_IP "echo 'SSH connection successful'"

          # Deploy application (your original steps)
          ssh -o StrictHostKeyChecking=no -v $SERVER_USER@$SERVER_IP << 'EOF'
            set -e  # Stop script on error

            # Ensure the directory exists
            if [ ! -d "/var/www/calculator" ]; then
              echo "Directory /var/www/calculator not found. Cloning repository..."
              sudo mkdir -p /var/www/calculator
              sudo chown -R $USER:$USER /var/www/calculator
              cd /var/www/calculator
              git clone https://github.com/anderswith/calculatordevops.git .  # Adjust this URL to your repo
            else
              echo "Navigating to /var/www/calculator and pulling the latest code..."
              cd /var/www/calculator || exit 1
              git pull origin main || exit 1
            fi

            echo "Building the .NET app..."
            dotnet build || exit 1  # Fail if build fails

            echo "Reloading systemd and restarting the calculator service..."
            sudo systemctl daemon-reload || exit 1
            sudo systemctl restart calculator || exit 1

            # Check the status of the application
            sudo systemctl status calculator --no-pager || exit 1

            echo "✅ Deployment completed successfully!"
          EOF
