name: tester.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Set up SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          SERVER_USER: ${{ vars.STAGING_SERVER_USERNAME }}
          SERVER_IP: ${{ vars.STAGING_SERVER_IP }}
        
        run: |
          # Set up SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Building Angular frontend..."
          cd calculator-frontend-main
          npm install
          npm run build --prod  # Build the Angular app for production

          echo "Copying frontend build files to staging server..."
          scp -r dist/* $SERVER_USER@$SERVER_IP:/var/www/frontend/

          echo "Copying backend files to staging server..."
          scp -r DevOpsCalculator/* $SERVER_USER@$SERVER_IP:/home/$SERVER_USER/backend/

          # SSH into server to set up the backend
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            set -e  # Stop script if an error occurs

            # Move to the backend directory and compile
            cd /home/$SERVER_USER/backend
            dotnet publish -c Release -o ./publish

            # Run the backend application in the background
            echo "Running backend..."
            cd publish
            nohup dotnet DevOpsCalculator.dll &  # Run in the background

            # Check status of the backend
            ps aux | grep 'DevOpsCalculator.dll'

            echo "✅ Deployment completed successfully!"
          EOF


