on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          SERVER_USER: ${{ secrets.STAGING_SERVER_USERNAME }}
          SERVER_IP: ${{ secrets.STAGING_SERVER_IP }}
        
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
            set -e  # Stop scriptet ved fejl
            cd /var/www/calculator
            git pull origin main
            dotnet build
            sudo systemctl daemon-reload  # Sørg for at servicefilen er opdateret
            sudo systemctl restart calculator
            sudo systemctl status calculator --no-pager
            echo "✅ Deployment completed successfully!"
          EOF
